name:                haskell-template
version:             0.1.0.0
github:              "githubuser/haskell-template"
license:             MIT
author:              "Thomas Hügel"
copyright:           "2023 Thomas Hügel + 2022 Sridhar Ratnakumar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-template#readme>

dependencies:
- name: base 
  version: ">= 4.7 && < 5"
  mixin:
    - hiding (Prelude)
- name: relude
  mixin:
    - (Relude as Prelude, Relude.Container.One)

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  toto-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-template

tests:
  toto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-template
